#!/bin/bash

# Instructions for creating the GitHub repository
echo "GitHub Repository Setup Instructions"
echo "====================================="
echo ""
echo "Since the GitHub CLI (gh) is not installed, please follow these steps:"
echo ""
echo "Option 1: Install GitHub CLI and run automatically"
echo "  1. Install gh: https://github.com/cli/cli#installation"
echo "  2. Authenticate: gh auth login"
echo "  3. Create repo: gh repo create deepseek-ocr --private --source=. --remote=origin"
echo "  4. Push: git push -u origin master"
echo ""
echo "Option 2: Create repository manually via web interface"
echo "  1. Go to: https://github.com/new"
echo "  2. Repository name: deepseek-ocr"
echo "  3. Description: Batch OCR processing tool using DeepSeek-OCR model via vLLM, optimized for Nvidia DGX Spark"
echo "  4. Select: Private"
echo "  5. Do NOT initialize with README, .gitignore, or license"
echo "  6. Click 'Create repository'"
echo "  7. Run these commands:"
echo ""
echo "     git remote add origin https://github.com/YOUR_USERNAME/deepseek-ocr.git"
echo "     git branch -M main"
echo "     git push -u origin main"
echo ""
echo "Option 3: Use SSH (if you have SSH keys configured)"
echo "  1. Follow Option 2 steps 1-6"
echo "  2. Run these commands:"
echo ""
echo "     git remote add origin git@github.com:YOUR_USERNAME/deepseek-ocr.git"
echo "     git branch -M main"
echo "     git push -u origin main"
echo ""
echo "====================================="
echo "Current repository status:"
git log --oneline -1
echo ""
echo "Branch: $(git branch --show-current)"
